# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 14:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_Remote_Units_Annotation_Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'annotation_remote_units_annotation_units',
            },
        ),
        migrations.CreateModel(
            name='Annotation_Units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annotation_unit_tree_id', models.CharField(default='1', max_length=200)),
                ('type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('IMPLICIT', 'REGULAR')], max_length=50)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('gui_status', models.CharField(choices=[('OPEN', 'Open'), ('COLLAPSE', 'Collapse'), ('HIDDEN', 'Hidden')], max_length=50)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Annotation_Units')),
            ],
            options={
                'db_table': 'annotation_units',
            },
        ),
        migrations.CreateModel(
            name='Annotation_Units_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'annotation_units_categories',
            },
        ),
        migrations.CreateModel(
            name='Annotation_Units_Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'annotation_units_tokens',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20000)),
                ('tooltip', models.CharField(max_length=500)),
                ('is_default', models.NullBooleanField()),
                ('abbreviation', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Derived_Layers_Categories_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='category_id', to='uccaApp.Categories')),
            ],
            options={
                'db_table': 'derived_layers_categories_categories',
            },
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ROOT', 'Root'), ('REFINEMENT', 'Refinement'), ('EXTENSION', 'Extension'), ('COARSENING', 'Coarsening')], default=1, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20000)),
                ('tooltip', models.CharField(max_length=500)),
                ('slotted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_layer_id', models.ForeignKey(blank=True, db_column='parent_layer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_id', to='uccaApp.Layers')),
            ],
            options={
                'db_table': 'layers',
            },
        ),
        migrations.CreateModel(
            name='Layers_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shortcut_key', models.CharField(blank=True, db_column='category_shortcut_key', max_length=50, null=True)),
                ('was_default', models.BooleanField()),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='layers_categories_category_id', to='uccaApp.Categories')),
                ('layer_id', models.ForeignKey(db_column='layer_id', on_delete=django.db.models.deletion.PROTECT, related_name='layers_categories_layer_id', to='uccaApp.Layers')),
            ],
            options={
                'db_table': 'layers_categories',
            },
        ),
        migrations.CreateModel(
            name='Layers_Categories_Restrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resriction_type', models.CharField(choices=[('FORBID_ANY_CHILD', 'forbid any child'), ('FORBID_CHILD', 'forbid child'), ('REQUIRE_CHILD', 'require child'), ('FORBID_SIBILIMG', 'forbid sibilimg'), ('REQUIRE_SIBLING', 'require sibling')], max_length=256)),
                ('category_ids1', models.CharField(max_length=100000)),
                ('category_ids2', models.CharField(max_length=100000)),
                ('layer_id', models.ForeignKey(db_column='layer_id', on_delete=django.db.models.deletion.PROTECT, related_name='resriction_layer_id', to='uccaApp.Layers')),
            ],
            options={
                'db_table': 'layers_categories_restrictions',
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(default='', max_length=100)),
                ('data', models.CharField(default='', max_length=100000)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_action',
            },
        ),
        migrations.CreateModel(
            name='LogLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(default='', max_length=100)),
                ('action', models.CharField(default='', max_length=100)),
                ('data', models.CharField(default='', max_length=1000)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_login',
            },
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50000)),
                ('type', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passages',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20000)),
                ('tooltip', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(db_column='layer_id', default='', on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Layers')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('GUEST', 'Guest'), ('PROJECT_MANAGER', 'Project Manager'), ('ADMIN', 'Admin'), ('ANNOTATOR', 'Annotator')], max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Roles_Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Roles')),
            ],
            options={
                'db_table': 'roles_tabs',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(default='', max_length=20000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('TASKS', 'Tasks'), ('SOURCES', 'Sources'), ('PASSAGES', 'Passages'), ('PROJECTS', 'Projects'), ('LAYERS', 'Layers'), ('USERS', 'Users')], max_length=50)),
            ],
            options={
                'db_table': 'tabs',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ANNOTATION', 'annotation'), ('TOKENIZATION', 'Tokenization'), ('REVIEW', 'review')], db_column='task_type', default=1, max_length=256)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('SUBMITTED', 'SUBMITTED'), ('ONGOING', 'ONGOING'), ('REJECTED', 'REJECTED')], max_length=256)),
                ('is_demo', models.BooleanField()),
                ('manager_comment', models.CharField(default='', max_length=1000)),
                ('user_comment', models.CharField(default='', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('out_of_date', models.BooleanField(default=False)),
                ('obseleted_by', models.IntegerField(default=None, null=True)),
                ('parent_obseleted_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('require_annotation', models.BooleanField()),
                ('text', models.CharField(max_length=50)),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Tasks')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(db_column='role', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Roles')),
                ('user_auth', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='annotator',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='uccaApp.Users'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent_task',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_id', to='uccaApp.Tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='passage',
            field=models.ForeignKey(blank=True, db_column='passage_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Passages'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(db_column='project_id', default='', on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Projects'),
        ),
        migrations.AddField(
            model_name='roles_tabs',
            name='tab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Tabs'),
        ),
        migrations.AddField(
            model_name='passages',
            name='source',
            field=models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Sources'),
        ),
        migrations.AddField(
            model_name='derived_layers_categories_categories',
            name='layer_id',
            field=models.ForeignKey(db_column='layer_id', on_delete=django.db.models.deletion.PROTECT, related_name='layer_id', to='uccaApp.Layers'),
        ),
        migrations.AddField(
            model_name='derived_layers_categories_categories',
            name='parent_category_id',
            field=models.ForeignKey(db_column='parent_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='parent_category_id', to='uccaApp.Categories'),
        ),
        migrations.AddField(
            model_name='annotation_units_tokens',
            name='token_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Tokens'),
        ),
        migrations.AddField(
            model_name='annotation_units_tokens',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Annotation_Units'),
        ),
        migrations.AddField(
            model_name='annotation_units_categories',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Categories'),
        ),
        migrations.AddField(
            model_name='annotation_units_categories',
            name='remote_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_parent_id', to='uccaApp.Annotation_Units'),
        ),
        migrations.AddField(
            model_name='annotation_units_categories',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_id', to='uccaApp.Annotation_Units'),
        ),
        migrations.AddField(
            model_name='annotation_units',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Tasks'),
        ),
        migrations.AddField(
            model_name='annotation_remote_units_annotation_units',
            name='remote_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_unit_id', to='uccaApp.Annotation_Units'),
        ),
        migrations.AddField(
            model_name='annotation_remote_units_annotation_units',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_unit_id', to='uccaApp.Annotation_Units'),
        ),
        migrations.AlterUniqueTogether(
            name='roles_tabs',
            unique_together=set([('role_id', 'tab_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='layers_categories',
            unique_together=set([('category_id', 'layer_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='derived_layers_categories_categories',
            unique_together=set([('layer_id', 'parent_category_id', 'category_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation_units_tokens',
            unique_together=set([('unit_id', 'token_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation_units_categories',
            unique_together=set([('unit_id', 'category_id', 'remote_parent_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation_units',
            unique_together=set([('id', 'task_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation_remote_units_annotation_units',
            unique_together=set([('unit_id', 'remote_unit_id')]),
        ),
    ]
