# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0002_auto_20180201_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='obseleted_by',
            new_name='obsoleted_by',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='parent_obseleted_by',
            new_name='parent_obsoleted_by',
        ),
        migrations.AddField(
            model_name='annotation_units',
            name='cluster',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_metacategory',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='layers',
            name='category_reorderings',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='passages',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
