# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0002_auto_20171203_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_units',
            name='gui_status',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('COLLAPSE', 'Collapse'), ('OPEN', 'Open')], max_length=50),
        ),
        migrations.AlterField(
            model_name='annotation_units',
            name='type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('IMPLICIT', 'REGULAR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='layers',
            name='type',
            field=models.CharField(choices=[('COARSENING', 'Coarsening'), ('EXTENSION', 'Extension'), ('REFINEMENT', 'Refinement'), ('ROOT', 'Root')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='layers_categories_restrictions',
            name='resriction_type',
            field=models.CharField(choices=[('FORBID_CHILD', 'forbid child'), ('FORBID_SIBILIMG', 'forbid sibilimg'), ('FORBID_ANY_CHILD', 'forbid any child'), ('REQUIRE_CHILD', 'require child'), ('REQUIRE_SIBLING', 'require sibling')], max_length=256),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('ADMIN', 'Admin'), ('ANNOTATOR', 'Annotator'), ('GUEST', 'Guest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(choices=[('SOURCES', 'Sources'), ('TASKS', 'Tasks'), ('PASSAGES', 'Passages'), ('USERS', 'Users'), ('LAYERS', 'Layers'), ('PROJECTS', 'Projects')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('REVIEW', 'review'), ('TOKENIZATION', 'Tokenization'), ('ANNOTATION', 'annotation')], db_column='task_type', default=1, max_length=256),
        ),
    ]
