# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0002_auto_20180130_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='layers',
            name='category_reorderings',
            field=models.TextField(default='', null=True),
        ),
    ]
