# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0002_auto_20180131_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation_units',
            name='cluster',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_metacategory',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='passages',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
