# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0003_auto_20180131_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation_units',
            old_name='annotation_unit_tree_id',
            new_name='tree_id',
        ),
    ]
