# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0003_auto_20171206_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_units',
            name='gui_status',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('OPEN', 'Open'), ('COLLAPSE', 'Collapse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='layers',
            name='type',
            field=models.CharField(choices=[('COARSENING', 'Coarsening'), ('REFINEMENT', 'Refinement'), ('EXTENSION', 'Extension'), ('ROOT', 'Root')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='layers_categories_restrictions',
            name='resriction_type',
            field=models.CharField(choices=[('FORBID_SIBILIMG', 'forbid sibilimg'), ('FORBID_ANY_CHILD', 'forbid any child'), ('FORBID_CHILD', 'forbid child'), ('REQUIRE_CHILD', 'require child'), ('REQUIRE_SIBLING', 'require sibling')], max_length=256),
        ),
        migrations.AlterField(
            model_name='passages',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('ADMIN', 'Admin'), ('GUEST', 'Guest'), ('ANNOTATOR', 'Annotator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(choices=[('SOURCES', 'Sources'), ('PROJECTS', 'Projects'), ('USERS', 'Users'), ('LAYERS', 'Layers'), ('PASSAGES', 'Passages'), ('TASKS', 'Tasks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'REJECTED'), ('ONGOING', 'ONGOING'), ('SUBMITTED', 'SUBMITTED'), ('NOT_STARTED', 'NOT_STARTED')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('ANNOTATION', 'annotation'), ('REVIEW', 'review'), ('TOKENIZATION', 'Tokenization')], db_column='task_type', default=1, max_length=256),
        ),
    ]
