# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0004_auto_20180201_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation_units',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation_units',
            name='type',
            field=models.CharField(choices=[('IMPLICIT', 'IMPLICIT'), ('REGULAR', 'REGULAR')], max_length=50),
        ),
    ]
