# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0004_auto_20171206_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_units',
            name='gui_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COLLAPSE', 'Collapse'), ('HIDDEN', 'Hidden')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layers',
            name='type',
            field=models.CharField(choices=[('EXTENSION', 'Extension'), ('COARSENING', 'Coarsening'), ('REFINEMENT', 'Refinement'), ('ROOT', 'Root')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='layers_categories_restrictions',
            name='resriction_type',
            field=models.CharField(choices=[('FORBID_CHILD', 'forbid child'), ('FORBID_ANY_CHILD', 'forbid any child'), ('REQUIRE_CHILD', 'require child'), ('REQUIRE_SIBLING', 'require sibling'), ('FORBID_SIBILIMG', 'forbid sibilimg')], max_length=256),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANNOTATOR', 'Annotator'), ('PROJECT_MANAGER', 'Project Manager'), ('GUEST', 'Guest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(choices=[('TASKS', 'Tasks'), ('USERS', 'Users'), ('PASSAGES', 'Passages'), ('LAYERS', 'Layers'), ('SOURCES', 'Sources'), ('PROJECTS', 'Projects')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('NOT_STARTED', 'NOT_STARTED'), ('REJECTED', 'REJECTED'), ('ONGOING', 'ONGOING')], max_length=256),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('TOKENIZATION', 'Tokenization'), ('ANNOTATION', 'annotation'), ('REVIEW', 'review')], db_column='task_type', default=1, max_length=256),
        ),
    ]
