# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0005_auto_20171211_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_units',
            name='gui_status',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('OPEN', 'Open'), ('COLLAPSE', 'Collapse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='annotation_units',
            name='type',
            field=models.CharField(choices=[('IMPLICIT', 'REGULAR'), ('REGULAR', 'REGULAR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layers',
            name='type',
            field=models.CharField(choices=[('COARSENING', 'Coarsening'), ('REFINEMENT', 'Refinement'), ('ROOT', 'Root'), ('EXTENSION', 'Extension')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='layers_categories_restrictions',
            name='resriction_type',
            field=models.CharField(choices=[('FORBID_ANY_CHILD', 'forbid any child'), ('REQUIRE_SIBLING', 'require sibling'), ('FORBID_SIBILIMG', 'forbid sibilimg'), ('FORBID_CHILD', 'forbid child'), ('REQUIRE_CHILD', 'require child')], max_length=256),
        ),
        migrations.AlterField(
            model_name='passages',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('ANNOTATOR', 'Annotator'), ('PROJECT_MANAGER', 'Project Manager'), ('ADMIN', 'Admin'), ('GUEST', 'Guest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tabs',
            name='name',
            field=models.CharField(choices=[('PASSAGES', 'Passages'), ('USERS', 'Users'), ('LAYERS', 'Layers'), ('TASKS', 'Tasks'), ('SOURCES', 'Sources'), ('PROJECTS', 'Projects')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'REJECTED'), ('NOT_STARTED', 'NOT_STARTED'), ('SUBMITTED', 'SUBMITTED'), ('ONGOING', 'ONGOING')], max_length=256),
        ),
    ]
