# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 07:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0005_auto_20180709_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_Json',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annotation_json', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.PROTECT, to='uccaApp.Tasks')),
            ],
            options={
                'db_table': 'annotation_json',
            },
        ),
    ]
