# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0005_auto_20180709_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
