# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0006_annotation_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='annotation_json',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Annotation_Json'),
        ),
        migrations.AlterField(
            model_name='annotation_json',
            name='annotation_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='annotation_json',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='annotation_json',
            name='task',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uccaApp.Tasks'),
        ),
    ]
