# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0007_auto_20181205_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_json',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
