# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0007_auto_20171211_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='obseleted_by',
            new_name='obsoleted_by',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='parent_obseleted_by',
            new_name='parent_obsoleted_by',
        ),
    ]
