# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0008_auto_20171228_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_metacategory',
            field=models.NullBooleanField(),
        ),
    ]
