# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0008_auto_20181205_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
