# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0009_auto_20181226_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='passages',
            name='text_direction',
            field=models.CharField(choices=[('RTL', 'RTL'), ('LTR', 'LTR')], default='LTR', max_length=3),
        ),
    ]
