# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0010_tasks_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='cluster',
        ),
    ]
