# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0011_auto_20190402_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layers',
            name='require_all_tokens_covered',
            field=models.BooleanField(default=True),
        ),
    ]
