# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uccaApp', '0013_auto_20190402_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens_Json',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uccaApp.Tasks')),
            ],
            options={
                'db_table': 'tokens_json',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='tokens_json',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uccaApp.Tokens_Json'),
        ),
    ]
