dist: trusty
jobs:
  include:
    - env: TEST=server
      language: python
      python: 3.6
      services:
        - postgresql
      install:
        - cd Server
        - pip install -r requirements.txt
      before_script:
        - mv ucca/settings-test.py ucca/local_settings.py
        - psql -c 'CREATE DATABASE ucca_test;' -U postgres
        - psql -c 'CREATE SCHEMA ucca;' -U postgres -d ucca_test
        - psql -c 'CREATE USER pr_ucca SUPERUSER CREATEDB CREATEROLE LOGIN;' -U postgres -d ucca_test
        - python manage.py makemigrations
        - python manage.py migrate
        - python manage.py loaddata tabs
        - python manage.py loaddata roles
        - python manage.py loaddata roles_tabs
        - python manage.py loaddata permissions
        - python manage.py loaddata groups_permissions_admin
        - python manage.py loaddata categories
        - python manage.py loaddata sources
        - python manage.py loaddata passages
        - python manage.py loaddata superuser
      script:
        - python manage.py runserver &
    - env: TEST=client
      language: node_js
      node_js: 8.6
      install:
        - cd Client
        - npm install bower
        - npm install
      script:
        - gulp inject
        - gulp serve:dist

