version: '2'

services:
  ucca-db:
    image: uccaproject/ucca-db
    expose:
      - "5432"
    ports:
      - "15432:5432"
    volumes:
      - ucca-volume:/var/lib/postgresql/data

  ucca-backend:
    image: uccaproject/ucca-backend
    expose:
      - "8000"
    ports:
      - "8085:8000"
    depends_on:
      - ucca-db  

  ucca-webserver:
    image: uccaproject/ucca-frontend
    expose:
      - "80"
    ports:
      - "6080:80"
    depends_on:
      - ucca-backend
        
volumes:
  ucca-volume:
