version: '3'

services:
  ucca-db:
    image: postgres:11
    ports:
      - "15433:5432"
    volumes:
      - ucca-db-volume:/var/lib/postgresql/data
      - ./init.db:/docker-entrypoint-initdb.d
      - ./restore.backup:/restore.backup
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ucca

volumes:
  ucca-db-volume: